wasm_dir = "wasm"

[ledger]
genesis_time = "1970-01-01T00:00:00Z"
chain_id = "namada-internal.00000000000000"

[ledger.shell]
base_dir = ".namada"
ledger_address = "127.0.0.1:26658"
storage_read_past_height_limit = 3600
db_dir = "db"
tendermint_dir = "tendermint"

[ledger.tendermint]
rpc_address = "127.0.0.1:26657"
p2p_address = "127.0.0.1:26656"
p2p_persistent_peers = []
p2p_pex = true
p2p_allow_duplicate_ip = false
p2p_addr_book_strict = true
consensus_timeout_commit = "1000ms"
tendermint_mode = "Full"
instrumentation_prometheus = false
instrumentation_prometheus_listen_addr = "127.0.0.1:26661"
instrumentation_namespace = "namadan_tm"
tx_index = false
